# Generated by Django 4.1.3 on 2024-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modifided_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
