# Generated by Django 4.1.3 on 2024-06-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_post_likes_count_like_like_unique_user_post_like'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_post_like',
        ),
    ]
